name: Update gist with WakaTime stats

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # kst 6am
    - cron: "0 21 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update-gist
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 58909d6332ce0ce537b3e2de2551c30d
      GIST_BARSTYLE: SOLIDLT
      GIST_BARLENGTH: -1
      GIST_TIMESTYLE: SHORT

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ^1.14

      - uses: actions/checkout@v4

      - name: Update-gist
        run: go run ./cmd/box/main.go 
